version: '3'



services:
  mysql:
    hostname: mysql
    container_name: mysql
    restart: always
    image: mysql:8.0.37-debian
    environment:
      MYSQL_DATABASE: orders
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 3

  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    restart: always
    image: rabbitmq:3.12.14-management-alpine
    ports:
      - 5672:5672
      - 15672:15672
      - 15692:15692
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 3